# Copyright (C) 2008-2015, Marvell International Ltd.
# All Rights Reserved.

exec-y += ssp_display_demo
ssp_display_demo-objs-y :=  src/main.c src/display.c
ssp_display_demo-cflags-y := -I$(d)/src -Wno-packed-bitfield-compat

# Applications could also define custom board files if required using following:
#ssp_display_demo-board-y := /path/to/boardfile
